name: dartotsu
description: "An Anilist client"

publish_to: 'none'

# Application version and build number
version: 0.0.3+1

# Dart SDK constraints
environment:
  sdk: '>=3.4.3 <4.0.0'

# Main dependencies
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  async: ^2.13.0
  # State Management
  provider: ^6.1.5
  get: ^4.7.2

  # Networking
  shorebird_code_push: ^2.0.4
  http: ^1.4.0
  web_socket_channel: ^3.0.3
  http_interceptor: ^2.0.0

  # JSON Serialization
  json_annotation: ^4.9.0

  # Local Storage
  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  path_provider: ^2.1.5
  path: ^1.9.1

  # UI Components
  flutter_animate: ^4.5.2
  expandable_widgets: ^1.0.3+1
  expandable_text: 2.3.0
  cached_network_image: ^3.4.1
  precached_network_image: ^1.2.4
  flutter_svg: ^2.2.0
  flex_color_picker: ^3.7.1
  flutter_markdown: ^0.7.7+1
  icons_plus: ^5.0.0
  skeletonizer: ^2.1.0+1
  blurbox: ^0.0.6
  # UI Enhancements
  blur: ^4.0.2
  expandable_page_view: ^1.0.17
  carousel_slider: ^5.1.1
  flutter_staggered_grid_view: ^0.7.0
  scrollable_positioned_list: ^0.3.8
  html: ^0.15.6
  intl: ^0.20.2
  # Platform Specific
  media_kit:
    git:
      url: https://github.com/Schnitzel5/media-kit.git
      path: media_kit
  media_kit_video:
    git:
      url: https://github.com/Schnitzel5/media-kit.git
      path: media_kit_video
  media_kit_libs_video:
    git:
      url: https://github.com/Schnitzel5/media-kit.git
      path: libs/universal/media_kit_libs_video
  window_manager: ^0.5.0
  permission_handler: ^12.0.0+1
  flutter_inappwebview: ^6.2.0-beta.2
  desktop_webview_window:
    git:
      url: https://github.com/kodjodevf/desktop_webview_window.git
      path: packages/desktop_webview_window
      ref: main
  wakelock_plus: ^1.3.2
  volume_controller: ^3.4.0 #dont change
  screen_brightness: ^2.1.4 #dont change
  app_links: ^6.4.0
  win32: ^5.14.0
  ffi: ^2.1.4

  # Miscellaneous
  device_info_plus: ^11.5.0
  package_info_plus: ^8.3.0
  file_picker: ^10.2.0
  share_plus: ^11.0.0
  url_launcher: ^6.3.1
  dynamic_color: ^1.7.0
  json_path: ^0.7.6
  grouped_list: ^6.0.0
  fuzzywuzzy: ^1.2.0
  collection: ^1.19.1
  flutter_web_auth_2: ^4.1.0
  flutter_dotenv: ^5.2.1
  dartotsu_extension_bridge:
    git:
     url: https://github.com/aayush2622/DartotsuExtensionBridge.git
     ref: master
    #path: ../DartotsuExtensionBridge

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  
  # Code Generation
  isar_generator: ^3.1.0+1
  json_serializable: ^6.0.1
  build_runner: ^2.5.3
  inno_bundle: ^0.9.0
dependency_overrides:
  analyzer: ">=5.2.0 <7.0.0"
  js: ">=0.6.3 <0.7.1"
  collection: ^1.19.1
  desktop_webview_window: ^0.2.3

# Flutter-specific configurations
flutter:
  uses-material-design: true
  generate: true
  # Fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins.ttf
        - asset: assets/fonts/poppins_bold.ttf
          weight: 700
        - asset: assets/fonts/poppins_semi_bold.ttf
          weight: 600
        - asset: assets/fonts/poppins_thin.ttf
          weight: 100
    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/poppins_semi_bold.ttf

  # Assets
  assets:
    - .env
    - assets/images/logo.png
    - assets/svg/bmc-button.svg
    - assets/svg/anilist.svg
    - assets/svg/discord.svg
    - assets/svg/kitsu.svg
    - assets/svg/mal.svg
    - assets/svg/simkl.svg
    - assets/svg/extensions.svg
    - assets/svg/incognito.svg
    - shorebird.yaml
# Flutter Launcher Icons Configuration
# dart run flutter_launcher_icons
flutter_icons:
  ios: true
  image_path: "assets/images/logo.png"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
  web:
    generate: true
    image_path: "assets/images/logo.png"
  macos:
    generate: true
    image_path: "assets/images/logo.png"

inno_bundle:
  sign_tool:
    command: $p
  id: 609d9fb9-ac99-533b-a5b5-f277afa99b68 # <-- Put your app id here
  publisher: Ankit Grai # Optional, but recommended.
  name: Dartotsu # Also optional, but recommended.
  version: 0.0.3 # Optional, but recommended.
  admin: auto
  installer_icon: assets/images/lol.ico
  languages: # Arabic was causing issues so switched to only English for installer
    - english
